version: "3.9"
services:
  nginx:
    container_name: nginx
    build: ./deploy2/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
  php:
    container_name: php
    build: 
        context: .
        dockerfile: Dockerfile2
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
