version: "3.9"
services:
        web:
                build: .
                #                deploy: 
                #                         mode: replicated
                #                         replicas: 3
                ports:
                - "80:80"
                - "443:443"

