version: "3"
services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile2
    volumes:
      - ./:/var/www/html
    expose:
      - "9000"
  nginx:
    build: ./deploy2/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
    depends_on:
      - php-fpm

